### ISSUE TITLE
[Feature] Plotsquared V6 Support

### ISSUE THREAD

**Issue by OnlyPW** [Ghost-chu/QuickShop-Reremake#1200]
### Describe the Feature:
Please update Plotsquared V6 integration.
without, plugin stop working

### Additional context:
[11:53:56 INFO]: [QuickShop] Registering PlotSquared integration
[11:53:56 ERROR]: Error occurred while enabling QuickShop v4.0.9.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/plotsquared/core/configuration/Caption
at org.maxgamer.quickshop.integration.plotsquared.PlotSquaredIntegrationV5.load(PlotSquaredIntegrationV5.java:99) ~[?:?]at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-769]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.plotsquared.core.configuration.Caption
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-769]
at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
... 16 more

at org.maxgamer.quickshop.integration.plotsquared.PlotSquaredIntegrationProxy.load(PlotSquaredIntegrationProxy.java:67) ~[?:?]
at org.maxgamer.quickshop.integration.IntegrationHelper.lambda$callIntegrationsLoad$0(IntegrationHelper.java:176) ~[?:?]
at java.util.HashMap$Values.forEach(HashMap.java:1067) ~[?:?]
at org.maxgamer.quickshop.integration.IntegrationHelper.callIntegrationsLoad(IntegrationHelper.java:171) ~[?:?]
at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:944) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-769]
[11:53:56 INFO]: [QuickShop] Disabling QuickShop v4.0.9.3
[11:53:56 INFO]: [QuickShop] QuickShop is finishing remaining work, this may need a while...
[11:53:56 ERROR]: Error occurred while disabling QuickShop v4.0.9.3 (Is it up to date?)

**Comment by sandtechnology** [comment]
Try 4.0.9.4:https://www.spigotmc.org/resources/quickshop-reremake-1-17-ready-multi-currency.62575/download?version=405437
