### ISSUE TITLE
[BUG][QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem

### ISSUE THREAD

**Issue by yuankun1** [Ghost-chu/QuickShop-Reremake#1269]
[02:11:39 ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem
com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutEntityDestroy.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
        at org.maxgamer.quickshop.shop.VirtualDisplayItem$PacketFactory.createFakeItemDestroyPacket(VirtualDisplayItem.java:461) ~[?:?]
        at org.maxgamer.quickshop.shop.VirtualDisplayItem$PacketFactory.testFakeItem(VirtualDisplayItem.java:326) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:360) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:107) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:742) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:773) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-91]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-91]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-91]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-91]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-91]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-91]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-91]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-91]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-91]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by sandtechnology** [comment]
Already fixed in the latest snapshot, will release a new version later
