### ISSUE TITLE
i have no idea but it is filling my console

### ISSUE THREAD

**Issue by Kenton126** [Ghost-chu/QuickShop-Reremake#132]
[Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to QuickShop vReremake 2.2.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.t(TileEntityHopper.java:220) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:135) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:670) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:369) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot.jar:git-Spigot-935adb3-a0e4747]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassCastException

**Comment by Ghost-chu** [comment]
update
