### ISSUE TITLE
[BUG] IllegalStateException: Listener has been cancelled. Create a new listener instead.

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#1360]
### Describe the bug:
This error spams 48 times during start-up initialization.

```
[00:27:00] [Protocol Worker #420 - QuickShop - [recv: , send: MAP_CHUNK[class=PacketPlayOutMapChunk, id=34]]/WARN]: [QuickShop] Plugin QuickShop v4.0.9.7-SNAPSHOT generated an exception while executing task 5871
java.lang.IllegalStateException: Listener has been cancelled. Create a new listener instead.
	at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:568) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1300]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1300]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### To Reproduce:
1. Use dev build 1486 (QuickShop-Remake-SNAPSHOT)
2. Use ProtocolLib dev 531
3. Start server.
4. See errors after post done initialization.

### Expected behavior:
No errors.

### Paste link:
Paste generated with dev 1456.
- https://paste.ubuntu.com/p/mzcKXD8nGg/

### Additional context:
Downgrading to the last successful build that compiled prior to the "full async" commits (https://github.com/Ghost-chu/QuickShop-Reremake/commit/db95303bc1ef9bab96fc45ab53dc40860382f4c0 and newer) (dev 1456 without it), the error doesn't occur.

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/1487/
How about this version?
