### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by log4b0at** [Ghost-chu/QuickShop-Reremake#155]
**Describe the bug**
I try to update a plugin that is a bridge between AreaShop and Quickshop 2.3.0 in Spigot 1.14.4

i have an issue when the server starting:
```
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.maxgamer.quickshop.Event.ShopCreateEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:618) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:556) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at com.mcsunnyside.qsareashop.QSRRAreaShopAddon.onEnable(QSRRAreaShopAddon.java:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
```

**To Reproduce**
1. Create a plugin that extends JavaPlugin and implements Listener
2. in the onEnable method, registerEvents(this, this)
3. Make an EventHandler method that handle ShopCreateEvent as argument

**Paste link:**
- The plugin: [https://github.com/Ghost-chu/AreaShop-Addon](https://github.com/Ghost-chu/AreaShop-Addon)

**Comment by Ghost-chu** [comment]
bug confirmed, i will fix it in next version

**Comment by log4b0at** [comment]
do the update is planned for soon?
