### ISSUE TITLE
Error occurred while enabling QuickShop v5.0.0.11[BUG] 

### ISSUE THREAD

**Issue by Darkside247** [Ghost-chu/QuickShop-Reremake#1584]
### Description

everytime we try to use the plugin we get the following error code:

[21:02:29 ERROR]: Error occurred while enabling QuickShop v5.0.0.11 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.maxgamer.quickshop.util.economyformatter.EconomyFormatter.lambda$reloadModule$0(EconomyFormatter.java:66) ~[QuickShop.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at org.maxgamer.quickshop.util.economyformatter.EconomyFormatter.reloadModule(EconomyFormatter.java:61) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.util.economyformatter.EconomyFormatter.<init>(EconomyFormatter.java:50) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.<init>(SimpleShopManager.java:102) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:859) ~[QuickShop.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-353]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[21:02:29 INFO]: [QuickShop] Disabling QuickShop v5.0.0.11

### Steps to reproduce

installed the plugin, worked fine for a couple of months 
stopped working 
runs errors if i attempt to run a command 

### Expected Behaviour

it to work 

### Screenshots

console errors as posted before 

### `/qs paste` URL

i can not use any commands

**Comment by Ghost-chu** [comment]
you have bad configure about currency-symbol in configuration, reset the config to make it work
