### ISSUE TITLE
QuickShop 1.3.0.2 MySQL issues

### ISSUE THREAD

**Issue by arboriginal** [Ghost-chu/QuickShop-Reremake#28]
(paperSpigot 1.13.2, build 444)

The plugin works like a charm with sqlite, but when trying to use a MySQL, I got some errors on startup. When first time launching (no tables in database), I receive a warning about "BLOB/TEXT column 'owner' used in key specification without a key length" (see #23). But now, the table seems to be created, so if it's only a warning, it's ok.

But when restarting the server, I got a message "qs_shop" already exists. I tried to stop the server, remove tables and relaunch, same warning and same error after restart. When removing the 3 tables (shops, messages and schedules), same. If only "shop" is removed, got message "Table 'messages' already exists" or "Table 'schedules' already exists".

So, for now, I go on to use Quickshop with SQLite.

@Ghost-chu : Maybe you can post an empty MySQL export to let me import it and check if it's only a bug during the creation step and if it works normally after. (and allow you to defer / ignore this issue if users encounter this problem can manually import the tables schema).

**Comment by Ghost-chu** [comment]
If you got ` "qs_shop" already exists` it was okay, because QuickShop will try create table when booting up.
Just ignore it.

**Comment by arboriginal** [comment]
Wow, what a quick response :)
I would like to edit my issue to say I've tried both `use-varchar` true and false values.

> QuickShop will try create table when booting up. Just ignore it.

I can't, just after the warning, I receive this:
```
[Server thread/INFO]: [QuickShop] Disabling QuickShop vReremake 1.3.0.2
[Server thread/ERROR]: [QuickShop] Error setting up database. Aborting plugin load.
```

and so:
```
[Server thread/ERROR]: Error occurred while enabling QuickShop vReremake 1.3.0.2 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register org.maxgamer.quickshop.Listeners.BlockListener@26f055bd while not enabled
```

I will try with export and let you know the result.

**Comment by Ghost-chu** [comment]
> Wow, what a quick response :)
> I would like to edit my issue to say I've tried both `use-varchar` true and false values.
> 
> > QuickShop will try create table when booting up. Just ignore it.
> 
> I can't, just after the warning, I receive this:
> 
> ```
> [Server thread/INFO]: [QuickShop] Disabling QuickShop vReremake 1.3.0.2
> [Server thread/ERROR]: [QuickShop] Error setting up database. Aborting plugin load.
> ```
> and so:
> 
> ```
> [Server thread/ERROR]: Error occurred while enabling QuickShop vReremake 1.3.0.2 (Is it up to date?)
> org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register org.maxgamer.quickshop.Listeners.BlockListener@26f055bd while not enabled
> ```
> I will try with export and let you know the result.

Because we have Github robot in discord channel :)
If i online, i will recive the alert:)

And this problem looks is your database configuration issue.  
Can you give me full errors log?

**Comment by arboriginal** [comment]
You can find it here (simply remove comments and hide my DB infos):
https://gist.github.com/arboriginal/e1178e5ac6f86c73127e510f33b60c13

**Comment by Ghost-chu** [comment]
Try lastet build 1.3.0.3

**Comment by arboriginal** [comment]
With 1.3.0.3, when using /qs export mysql
```
[16:39:28] [Server thread/WARN]: java.lang.NullPointerException
[16:39:28] [Server thread/WARN]: 	at org.maxgamer.quickshop.Database.Database.copyTo(Database.java:166)
[16:39:28] [Server thread/WARN]: 	at org.maxgamer.quickshop.Command.QS.export(QS.java:118)
[16:39:28] [Server thread/WARN]: 	at org.maxgamer.quickshop.Command.QS.onCommand(QS.java:585)
[16:39:28] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:39:28] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[16:39:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732)
[16:39:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:694)
[16:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:483)
[16:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440)
[16:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[16:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[16:39:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:39:28] [Server thread/INFO]: Failed to export to MySQL XXXXXXX@XXXXXXX.omgserv.com.XXXXXXX Reason: null
```

When starting with MySQL enabled, got error "com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'minecraft_206165.messages' doesn't exist", I suppose you forget to add prefix on this table.

Same after a restart after removing the 3 tables, but it says the plugin is loaded.
After another reboot, same warning, plugin loaded too.

I will test in game if it works and write to the database.

**Comment by Ghost-chu** [comment]
Asking in discord, close issue in Github
