### ISSUE TITLE
[BUG] Error occurred while enabling QuickShop v3.1.4.9 Util.InvaildIntegratedPluginClass: null

### ISSUE THREAD

**Issue by HL-Nya** [Ghost-chu/QuickShop-Reremake#350]
```
bug happens when server starts
Evn: paper 121 and spigot 1.15.2


```
[01:10:51] [Server thread/ERROR]: Error occurred while enabling QuickShop v3.1.4.9 (Is it up to date?)
org.maxgamer.quickshop.Util.InvaildIntegratedPluginClass: null
	at org.maxgamer.quickshop.Util.IntegrationHelper.register(IntegrationHelper.java:38) ~[?:?]
	at org.maxgamer.quickshop.QuickShop.registerIntegrations(QuickShop.java:659) ~[?:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:626) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-121]
	at java.lang.Thread.run(Thread.java:830) [?:?]

**Comment by sandtechnology** [comment]
Try to disable the all integration in config.yml, look like some integration class is missing annotation accidentally
