### ISSUE TITLE
Could not pass event InventoryMoveItemEvent

### ISSUE THREAD

**Issue by TheBarret** [Ghost-chu/QuickShop-Reremake#388]
Updated the plugin *26 to *27 and that didn't go all to well.
We run Spigot 1.15.2 and have the following plugins running along side:

`
LuckPerms, WorldEdit, PluginConstructorAPI, PlugMan, CrisTreeCapitator, Multiverse-Core, AsyncWorldEdit, PixelPrinter, CS-CoreLib, Multiverse-Portals, Vault, ColoredAnvils, PlayerParticles, GriefPrevention, QualityArmory, WorldEditSelectionVisualizer, NPCAuctions, Essentials, VeinMiner, KillerMoney, QuickShop, DeadChest, CommandSigns, DiscordSRV, MysqlEconomyBank, EssentialsChat
`

Exception thrown at startup:

`
 [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to QuickShop v3.1.4.27
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.TileEntityHopper.j(TileEntityHopper.java:199) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.TileEntityHopper.a(TileEntityHopper.java:135) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.TileEntityHopper.tick(TileEntityHopper.java:117) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.World.tickBlockEntities(World.java:617) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:418) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1082) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
`

**Comment by sandtechnology** [comment]
Could you provide paste link by /qs paste?

**Comment by sandtechnology** [comment]
https://www.spigotmc.org/resources/quickshop-reremake-1-15-ready-bees-bees-bee.62575/download?version=321309
Fixed
