### ISSUE TITLE
Some warn for 1.13.2

### ISSUE THREAD

**Issue by combrich** [Ghost-chu/QuickShop-Reremake#39]
There all warn include  "org.maxgamer.quickshop.Command.QS.signGUIApi"  call.

> [00:55:06] [Server thread/WARN]: [QuickShop] Task #7184 for QuickShop vReremake 1.3.1.8 generated an exception
java.lang.NullPointerException: null
	at org.maxgamer.quickshop.Command.QS.signGUIApi(QS.java:55) ~[?:?]
	at org.maxgamer.quickshop.QuickShop$1$1.run(QuickShop.java:200) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-470]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Warn2 

> [01:12:00] [Server thread/WARN]: [QuickShop] Task #7344 for QuickShop vReremake 1.3.1.8 generated an exception
java.lang.NullPointerException: null
	at org.maxgamer.quickshop.Command.QS.signGUIApi(QS.java:55) ~[?:?]
	at org.maxgamer.quickshop.QuickShop$1$1.run(QuickShop.java:200) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-470]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Warn3 

>  [QuickShop] Task #7388 for QuickShop vReremake 1.3.1.8 generated an exception
java.lang.NullPointerException: null
	at org.maxgamer.quickshop.Command.QS.signGUIApi(QS.java:55) ~[?:?]
	at org.maxgamer.quickshop.QuickShop$1$1.run(QuickShop.java:200) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-470]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Warn4
> [QuickShop] Task #7395 for QuickShop vReremake 1.3.1.8 generated an exception
java.lang.NullPointerException: null
	at org.maxgamer.quickshop.Command.QS.signGUIApi(QS.java:55) ~[?:?]
	at org.maxgamer.quickshop.QuickShop$1$1.run(QuickShop.java:200) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-470]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Warn5
>[01:31:53] [Server thread/WARN]: [QuickShop] Task #7396 for QuickShop vReremake 1.3.1.8 generated an exception
java.lang.NullPointerException: null
	at org.maxgamer.quickshop.Command.QS.signGUIApi(QS.java:55) ~[?:?]
	at org.maxgamer.quickshop.QuickShop$1$1.run(QuickShop.java:200) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-470]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Warn6:
>[QuickShop] Task #7399 for QuickShop vReremake 1.3.1.8 generated an exception
java.lang.NullPointerException: null
	at org.maxgamer.quickshop.Command.QS.signGUIApi(QS.java:55) ~[?:?]
	at org.maxgamer.quickshop.QuickShop$1$1.run(QuickShop.java:200) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-470]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-470]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by combrich** [comment]
thanks
