### ISSUE TITLE
[BUG] Null exception on InventoryCloseEvent from /enderchest

### ISSUE THREAD

**Issue by corexti** [Ghost-chu/QuickShop-Reremake#442]
When a player closes enderchest after opening it with a command (from Essentials), QuickShop throws an exception.

I'm assuming this error is also throwing random exceptions for other plugins on some event as it initially started occurring on this plugin.

Here's the error code:
*Note that I'm running latest version of QuickShop and Spigot.

`[13:34:45] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to QuickShop v4.0.2.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1251) ~[server_survival.jar:git-Spigot-2040c$
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1927) ~[?:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server_survival.jar:git-Spigot-2040c4c-893ad93]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_15_R1.InventoryEnderChest.getLocation(InventoryEnderChest.java:18) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.getLocation(CraftInventory.java:524) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        at org.maxgamer.quickshop.listener.PlayerListener.onInventoryClose(PlayerListener.java:236) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server_survival.jar:git-Spigot-2040c4c-893ad93]
        ... 18 more`

**Comment by sandtechnology** [comment]
https://cdn.discordapp.com/attachments/645891684277944320/703540414434508800/QuickShop-4.0.2.3-lab1.jar
In this lab version it has been fixed
