### ISSUE TITLE
[BUG] Console error when creating a shop

### ISSUE THREAD

**Issue by NemoCZmoravia** [Ghost-chu/QuickShop-Reremake#443]
**Describe the bug**
When I create a shop I get this error in the console.

**To Reproduce**
1. Create a shop
2. See the error in the console

**Expected behavior**
No error
**Screenshots**

**Paste link:**
https://paste.enginehub.org/bN3zKlNuc

**Additional context**

`[15:12:01 WARN]: java.lang.RuntimeException: Economy username cannot be null
[15:12:01 WARN]: at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:67)
[15:12:01 WARN]: at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:111)
[15:12:01 WARN]: at com.earth2me.essentials.api.Economy.add(Economy.java:174)
[15:12:01 WARN]: at com.earth2me.essentials.api.Economy.add(Economy.java:167)
[15:12:01 WARN]: at net.milkbowl.vault.economy.plugins.Economy_Essentials.tryDepositPlayer(Economy_Essentials.java:149)
[15:12:01 WARN]: at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:180)
[15:12:01 WARN]: at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50)
[15:12:01 WARN]: at org.maxgamer.quickshop.economy.Economy_Vault.deposit(Economy_Vault.java:112)
[15:12:01 WARN]: at org.maxgamer.quickshop.economy.Economy.deposit(Economy.java:55)
[15:12:01 WARN]: at org.maxgamer.quickshop.shop.ShopManager.actionCreate(ShopManager.java:814)
[15:12:01 WARN]: at org.maxgamer.quickshop.shop.ShopManager.lambda$handleChat$2(ShopManager.java:421)
[15:12:01 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[15:12:01 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[15:12:01 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240)
[15:12:01 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[15:12:01 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
[15:12:01 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[15:12:01 WARN]: at java.lang.Thread.run(Thread.java:748)
[15:12:01 WARN]: [QuickShop] This seems not QuickShop fault, you should cotact with your economy plugin author. (Essentials Economy)`

**Comment by sandtechnology** [comment]
Please set a valid tax account name or disable tax feature by set tax, cost to 0, and set price-change-requires-fee to false in config.yml
