### ISSUE TITLE
[BUG] Memory leak on startup updating from old version

### ISSUE THREAD

**Issue by quiquelhappy** [Ghost-chu/QuickShop-Reremake#480]
**Describe the bug**
I've updated the plugin from QuickShop 3.x to 4.0.2.12, and now I get console spam on startup.

**To Reproduce**
1. Go to plugins folder, update to 4.0.2.12
2. Start the server

**Expected behavior**
No console spam and memory leak, normal bahavior

**Paste link:**
Not possible to execute /qs paste, the startup causes a memory leak loop, you can see a startup log here: [https://pastebin.com/jXisEkZC](https://pastebin.com/jXisEkZC)

**Additional context**
Thread causing the memory leak
```
[18:09:05] [Craft Scheduler Thread - 43/WARN]: [QuickShop] Plugin QuickShop v4.0.2.12 generated an exception while executing task 641
java.lang.IllegalStateException: Asynchronous ChunkMapDistance::addTicket!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.addTicket(ChunkMapDistance.java:158) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.addTicket(ChunkMapDistance.java:311) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.addTicket(ChunkProviderServer.java:958) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:402) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:1016) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.Location.getChunk(Location.java:123) ~[patched_1.15.2.jar:git-Paper-345]
	at org.maxgamer.quickshop.shop.VirtualDisplayItem$1.lambda$onPacketSending$0(VirtualDisplayItem.java:332) ~[?:?]
	at org.maxgamer.quickshop.shop.VirtualDisplayItem$2.run(VirtualDisplayItem.java:368) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-345]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-345]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by sandtechnology** [comment]
Please try the newest version https://www.spigotmc.org/resources/quickshop-reremake-1-15-ready-bees-bees-bee.62575/download?version=336474

**Comment by quiquelhappy** [comment]
Hello, this fixed the issue, thank you!
