### ISSUE TITLE
[BUG] Erro when Disabling QuickShop v4.0.4.8

### ISSUE THREAD

**Issue by SrBedrock** [Ghost-chu/QuickShop-Reremake#550]
**Describe the bug**
Error on disable plugin.

**To Reproduce**
1. Stop the server.

**Expected behavior**
```
[21:43:46 INFO]: [QuickShop] Disabling QuickShop v4.0.4.8
[21:43:46 INFO]: [QuickShop] QuickShop is finishing remaining work, this may need a while...
[21:43:46 ERROR]: Error occurred while disabling QuickShop v4.0.4.8 (Is it up to date?)
java.lang.NullPointerException: null
at org.maxgamer.quickshop.QuickShop.onDisable(QuickShop.java:569) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.disablePlugins(CraftServer.java:434) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:775) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:700) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1048) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/135/
How about this version?

**Comment by SrBedrock** [comment]
> [ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/136](https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/136/)
> How about this version?

Problem solved!
