### ISSUE TITLE
[BUG] Java 1.16.1 "lost connection: Disconnected" when using the /qshop command

### ISSUE THREAD

**Issue by You0916** [Ghost-chu/QuickShop-Reremake#561]
**Describe the bug**
Java 1.16.1 "lost connection: Disconnected" when using the /qshop command

**To Reproduce**
Just type /qshop command, and I get lost.

**Expected behavior**
Open the shop

**Screenshots**
```
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[12:01:46 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:01:46 WARN]:        at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:01:46 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:01:46 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)

```

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/dC5gFG3DPz/

**Additional context**

**Comment by sandtechnology** [comment]
Please give the FULL Error, otherwise we can't help you

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
