### ISSUE TITLE
[BUG] Error using server command

### ISSUE THREAD

**Issue by zxc081003** [Ghost-chu/QuickShop-Reremake#563]
**Description error**
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/5177551/latest.log)

[12:58:29] [Server thread/information]: Sister_Xiaoxuan issued a server command: /qshop
[12:58:29] [Server thread/error]: empty
org.bukkit.command.CommandException: Unhandled exception of executing command'qshop' in the plugin QuickShop v4.0.4.9
        In org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        In org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        In org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670)~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.PlayerConnection.a (PlayerConnection.java:1510) ~ [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.PacketPlayInChat.a (PacketPlayInChat.java:47) ~ [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.PacketPlayInChat.a (PacketPlayInChat.java:1) ~ [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda $ 0 (PlayerConnectionUtils.java:13) ~ [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.TickTask.run (SourceFile: 18) [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask (SourceFile: 135) [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask (SourceFile: 23) [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext (SourceFile: 114) [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.MinecraftServer.aW (MinecraftServer.java:895) [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888)[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll (SourceFile: 99) [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick (MinecraftServer.java:871) [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In net.minecraft.server.v1_14_R1.MinecraftServer.run (MinecraftServer.java:805) [Spigot-1.14.2.jar: git-Spigot-df0eb25-da071ec]
        In java.lang.Thread.run (unknown source) [?: 1.8.0_261]
Cause: java.lang.ArrayIndexOutOfBoundsException: 0
        In org.maxgamer.quickshop.command.CommandManager.onCommand(CommandManager.java:353) ~[? :? ]
        At org.bukkit.command.PluginCommand.execute (PluginCommand.java:45) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
> More 17

**Reproduce**
1. Go to "Install Plugin"
2. Click "Restart Server"
3. Scroll down to "Go to the server to place instructions"
4. See the error "Error when issuing instructions"

**Expected behavior**
Hope we can do better

**Screenshot**
If applicable, please add screenshots to help explain your question.

![image](https://user-images.githubusercontent.com/55639947/92298128-4fabe200-ef78-11ea-9457-182febb7b089.png)

**Paste link:**
 Execute the command / qs paste, you will get a link containing server information, paste it under this text.
 You must create a paste unless the plugin is completely unusable.
 If the creation fails, you should find a paste file under the plugin/QuickShop folder.
-【Replace Paste Link】

https://paste.enginehub.org/A1yQDsXqL

**Other content**
Add any other context about the issue here.

**Comment by sandtechnology** [comment]
```
[12:41:21] [Server thread/ERROR]: [QuickShop] No Economy plugin detected, did you installed and loaded them? Make sure they loaded before QuickShop.
[12:41:21] [Server thread/ERROR]: [QuickShop] Install an economy plugin to get Vault or Reserve working.
```
Please install an Economy plugin, we will fix this tips bug in the next version.

**Comment by zxc081003** [comment]
[14:45:59] [Server thread/INFO]: Sister_Xiaoxuan issued server command: /qs
[14:45:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'qs' in plugin QuickShop v4.0.4.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.maxgamer.quickshop.command.CommandManager.onCommand(CommandManager.java:353) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        ... 17 more
>qs
[14:46:19] [Server thread/WARN]: Unexpected exception while parsing console command "qs"
org.bukkit.command.CommandException: Unhandled exception executing command 'qs' in plugin QuickShop v4.0.4.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.maxgamer.quickshop.command.CommandManager.onCommand(CommandManager.java:353) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        ... 8 more

Economy is installed, but still can’t be opened, error is displayed

**Comment by sandtechnology** [comment]
Vault is not an Economy plugin, is a bridge on economy plugin and permission plugin.

**Comment by zxc081003** [comment]
![image](https://user-images.githubusercontent.com/55639947/92299724-99e88f80-ef87-11ea-99e2-cb78f0fe47da.png)
![image](https://user-images.githubusercontent.com/55639947/92299729-a53bbb00-ef87-11ea-9ac2396d9629b983.png)
Economy and permissions installed

**Comment by sandtechnology** [comment]
For CMI, please read their instruction for using vault: https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/
