### ISSUE TITLE
Quickshop not working (no signs appearing and no shop created)

### ISSUE THREAD

**Issue by QcAng3Lz** [Ghost-chu/QuickShop-Reremake#570]
Hi, I'm trying to use QS on my 1.14.4 server but when I try creating a shop, it asks me for how much I want to sell the item, I do it in the chat and then nothing happens. No signs appear and I get an error in the command prompt.

Plugins: AsyncWorldEdit, CasinoPlugin, Citizen, CommandHook, CoreProtect, CustomItems, Denizen, DropHeads, ExssentialsX, GameModeInventories, Holograms, KeepChunks, LaggRemover, McMMO, Multiverse-Core, OldCombatMechanics, ProtocolLib, Quests, Residence, Sentinel, ServerListPlus, CommandSigns, UltraPermissions, Vault, WorldBorder,WorldEdit, WorldEditSelectionVisualiser.

Here's the error :

[02:48:50] [Server thread/WARN]: [QuickShop] Task #2626 for QuickShop v4.0.4.9 generated an exception
java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getEntityTypeModifier()Lcom/comphenix/protocol/reflect/StructureModifier;
at org.maxgamer.quickshop.shop.VirtualDisplayItem.initFakeDropItemPacket(VirtualDisplayItem.java:131) ~[?:?]
at org.maxgamer.quickshop.shop.VirtualDisplayItem.<init>(VirtualDisplayItem.java:94) ~[?:?]
at org.maxgamer.quickshop.shop.ContainerShop.initDisplayItem(ContainerShop.java:152) ~[?:?]
at org.maxgamer.quickshop.shop.ContainerShop.<init>(ContainerShop.java:129) ~[?:?]
at org.maxgamer.quickshop.shop.ShopManager.actionCreate(ShopManager.java:728) ~[?:?]
at org.maxgamer.quickshop.shop.ShopManager.lambda$handleChat$2(ShopManager.java:404) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by sandtechnology** [comment]
Please update ProtocolLib: https://www.spigotmc.org/resources/protocollib.1997/

**Comment by QcAng3Lz** [comment]
Thank you, you are a life saver!
