### ISSUE TITLE
[BUG] ConnectionIsUsingException on startup

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#650]
**Describe the bug**
Quickshop is throwing a `org.maxgamer.quickshop.database.DatabaseConnection$ConnectionIsUsingException: null` on startup (enable)

**To Reproduce**
1. Use QuickShop 4.0.5.2 on PaperMC 1.16.4 (Build 277)
2. Start server
3. See the error in the console

**Expected behavior**
No error

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.enginehub.org/gH3fxWpE8

**Additional context**

**Comment by sandtechnology** [comment]
Please provide the FULL error stacktrace, otherwise we can't help you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Andre601** [comment]
```
[16:38:36 WARN]: [QuickShop] Plugin QuickShop v4.0.5.2 generated an exception while executing task 2337
org.maxgamer.quickshop.database.DatabaseConnection$ConnectionIsUsingException: null
        at org.maxgamer.quickshop.database.DatabaseConnection.get(DatabaseConnection.java:48) ~[?:?]
        at org.maxgamer.quickshop.database.DatabaseHelper.selectTable(DatabaseHelper.java:231) ~[?:?]
        at org.maxgamer.quickshop.database.DatabaseHelper.selectAllShops(DatabaseHelper.java:238) ~[?:?]
        at org.maxgamer.quickshop.util.paste.Paste.genNewPaste(Paste.java:395) ~[?:?]
        at org.maxgamer.quickshop.util.SentryErrorReporter$1.run(SentryErrorReporter.java:120) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-277]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-277]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-277]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/292/
Is the issue fixed in this snapshot?

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/295/
It should actually fix it XD

**Comment by sandtechnology** [comment]
MultiThread should be the hardest part XD
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/298/
I'm sure it should fix it.
