### ISSUE TITLE
Plugin yml broke

### ISSUE THREAD

**Issue by Sykursen** [Ghost-chu/QuickShop-Reremake#69]
Hello,
Since the last update, my console return this error :
` [20:35:35 ERROR]: Could not load 'plugins/QuickShop-Reremake.1.4.2.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:166) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:140) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_212]
at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_212]
at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_212]
at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_212]
at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[Paper-1.13.2-b624.jar:git-Paper-624]
... 5 more`

**Comment by Mgazul** [comment]
Have you tried downloading the plugin again?

**Comment by Sykursen** [comment]
And the plugin still enable but the commands doesn't works.

**Comment by Mgazul** [comment]
Need more info: What is the command? Or provide the latest.log

**Comment by Sykursen** [comment]
> 
> 
> Have you tried downloading the plugin again?

I installed the plugin again and it works now. The file was corrupted during the transfer.
