### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SgtSquigles** [Ghost-chu/QuickShop-Reremake#723]
**Describe the bug**
So, in this plugin when you make a chest shop, the sign and anything about the shop just says "INVALED MESSAGE:"
**To Reproduce**
Just create a chest shop

**Expected behavior**
Not to see a warning sign.
**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- 【
![image](https://user-images.githubusercontent.com/75197904/100536030-b422ba00-31d2-11eb-932b-80d4d3afea4a.png)
】

**Additional context**

**Comment by Ghost-chu** [comment]
Try command "/qs reset messages" and "/qs reset lang" and also "/qs reset config"

**Comment by SgtSquigles** [comment]
> Try command "/qs reset messages" and "/qs reset lang" and also "/qs reset config"

Um it still didn't work when i ran all of the commands and it said "success" but I still got the same messages ;(

**Comment by Ghost-chu** [comment]
Try delete messages.json and execute "/qs reload"

**Comment by SgtSquigles** [comment]
> Try delete messages.json and execute "/qs reload"

hmm I'll try

**Comment by SgtSquigles** [comment]
> > Try delete messages.json and execute "/qs reload"
> 
> hmm I'll try

wait... how do i delete the message.json?

**Comment by SgtSquigles** [comment]
> Try delete messages.json and execute "/qs reload"

![image](https://user-images.githubusercontent.com/75197904/100538096-7594fb80-31e2-11eb-9ad6-1b3b3faac705.png)
So this is all i got when i ran that command.

**Comment by sandtechnology** [comment]
> 
> 
> > > Try delete messages.json and execute "/qs reload"
> > 
> > 
> > hmm I'll try
> 
> wait... how do i delete the message.json?

Please delete message.json in QuickShop folder and then execute `/qs reload`

**Comment by SgtSquigles** [comment]
> > > > Try delete messages.json and execute "/qs reload"
> > > 
> > > 
> > > hmm I'll try
> > 
> > 
> > wait... how do i delete the message.json?
> 
> Please delete `message.json` in QuickShop folder and then execute `/qs reload`

mk I'll try

**Comment by SgtSquigles** [comment]
> > > > Try delete messages.json and execute "/qs reload"
> > > 
> > > 
> > > hmm I'll try
> > 
> > 
> > wait... how do i delete the message.json?
> 
> Please delete `message.json` in QuickShop folder and then execute `/qs reload`

![image](https://user-images.githubusercontent.com/75197904/100538220-374c0c00-31e3-11eb-8e49-4f9ac7c769a5.png)
same thing

**Comment by sandtechnology** [comment]
Please create a paste link by `/qs paste`
And which version you are using?

**Comment by SgtSquigles** [comment]
> Please create a paste link by `/qs paste`
> And which version you are using?

What version do you  mean? Do you  mean game version? If so 1.16.3. and what link do you want me to paste?

**Comment by sandtechnology** [comment]
> 
> 
> > Please create a paste link by `/qs paste`
> > And which version you are using?
> 
> What version do you mean? Do you mean game version? If so 1.16.3. and what link do you want me to paste?

I mean Quickshop version, and after you executed `/qs paste`, you will get the only one link.

**Comment by SgtSquigles** [comment]
> > > Please create a paste link by `/qs paste`
> > > And which version you are using?
> > 
> > 
> > What version do you mean? Do you mean game version? If so 1.16.3. and what link do you want me to paste?
> 
> I mean Quickshop version, and after you executed `/qs paste`, you will get the only one link.

Oh okay hang on

**Comment by SgtSquigles** [comment]
4.0.5.3 is the plugin version. And when i ran the command this is what it said: 
![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)

**Comment by sandtechnology** [comment]
> 
> 
> 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)

Please upload the paste file, the file path is mentioned in this message.

**Comment by SgtSquigles** [comment]
> > > Please create a paste link by `/qs paste`
> > > And which version you are using?
> > 
> > 
> > What version do you mean? Do you mean game version? If so 1.16.3. and what link do you want me to paste?
> 
> I mean Quickshop version, and after you executed `/qs paste`, you will get the only one link, please provide it.

![image](https://user-images.githubusercontent.com/75197904/100538487-f35a0680-31e4-11eb-94db-529815a795f8.png)

**Comment by SgtSquigles** [comment]
oops

**Comment by SgtSquigles** [comment]
> > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> 
> Please upload the paste file, the file path is mentioned in this message.

okay

**Comment by SgtSquigles** [comment]
> > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> 
> Please upload the paste file, the file path is mentioned in this message.

XD how?

**Comment by sandtechnology** [comment]
> 
> 
> > > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> > 
> > 
> > Please upload the paste file, the file path is mentioned in this message.
> 
> XD how?

Just download it and then drag the file to the rely window....

**Comment by SgtSquigles** [comment]
> > > > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > > > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> > > 
> > > 
> > > Please upload the paste file, the file path is mentioned in this message.
> > 
> > 
> > XD how?
> 
> Just download it and then drag the file to the rely window....

... I'm dumb and all I'm seeing is a link that wont let me copy it

**Comment by sandtechnology** [comment]
> 
> 
> > > > > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > > > > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> > > > 
> > > > 
> > > > Please upload the paste file, the file path is mentioned in this message.
> > > 
> > > 
> > > XD how?
> > 
> > 
> > Just download it and then drag the file to the rely window....
> 
> ... I'm dumb and all I'm seeing is a link that wont let me copy it

Just wait for uploading and then comment : D

**Comment by SgtSquigles** [comment]
> > > > > > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > > > > > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> > > > > 
> > > > > 
> > > > > Please upload the paste file, the file path is mentioned in this message.
> > > > 
> > > > 
> > > > XD how?
> > > 
> > > 
> > > Just download it and then drag the file to the rely window....
> > 
> > 
> > ... I'm dumb and all I'm seeing is a link that wont let me copy it
> 
> Just wait for uploading and then comment : D

wdym?

**Comment by SgtSquigles** [comment]
> > > > > > > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > > > > > > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> > > > > > 
> > > > > > 
> > > > > > Please upload the paste file, the file path is mentioned in this message.
> > > > > 
> > > > > 
> > > > > XD how?
> > > > 
> > > > 
> > > > Just download it and then drag the file to the rely window....
> > > 
> > > 
> > > ... I'm dumb and all I'm seeing is a link that wont let me copy it
> > 
> > 
> > Just wait for uploading and then comment : D
> 
> wdym?

what do i do... just wait?

**Comment by sandtechnology** [comment]
> 
> 
> > > > > > > > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > > > > > > > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> > > > > > > 
> > > > > > > 
> > > > > > > Please upload the paste file, the file path is mentioned in this message.
> > > > > > 
> > > > > > 
> > > > > > XD how?
> > > > > 
> > > > > 
> > > > > Just download it and then drag the file to the rely window....
> > > > 
> > > > 
> > > > ... I'm dumb and all I'm seeing is a link that wont let me copy it
> > > 
> > > 
> > > Just wait for uploading and then comment : D
> > 
> > 
> > wdym?
> 
> what do i do... just wait?

If you can't upload file there, please go to our discord channel:https://discord.gg/QCbTXehj

**Comment by SgtSquigles** [comment]
> > > > > > > > > 4.0.5.3 is the plugin version. And when i ran the command this is what it said:
> > > > > > > > > ![image](https://user-images.githubusercontent.com/75197904/100538408-7af34580-31e4-11eb-88e1-f5046eab5fd3.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Please upload the paste file, the file path is mentioned in this message.
> > > > > > > 
> > > > > > > 
> > > > > > > XD how?
> > > > > > 
> > > > > > 
> > > > > > Just download it and then drag the file to the rely window....
> > > > > 
> > > > > 
> > > > > ... I'm dumb and all I'm seeing is a link that wont let me copy it
> > > > 
> > > > 
> > > > Just wait for uploading and then comment : D
> > > 
> > > 
> > > wdym?
> > 
> > 
> > what do i do... just wait?
> 
> If you can't upload file there, please go to our discord channel:https://discord.gg/QCbTXehj

sand, can you  please let me dm you?

**Comment by sandtechnology** [comment]
Close due to have solved in discord DM.
Just for record there, the source is class conflicting, from the server log I can see following errors and warnings:
```
[02:47:44] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[02:47:44] [Server thread/INFO]: [Geyser-Spigot]
[02:47:44] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser version 1.2.0-SNAPSHOT (git-master-894275b)
[02:47:44] [Server thread/INFO]: [Geyser-Spigot]
[02:47:44] [Server thread/INFO]: [Geyser-Spigot] ******************************************
**[02:48:29] [Server thread/WARN]: [Geyser-Spigot] Loaded class org.slf4j.LoggerFactory from QuickShop v4.0.5.3 which is not a depend, softdepend or loadbefore of this plugin.**
[02:48:29] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[02:48:29] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[02:48:29] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. 
===========================


[02:48:36] [Thread-20/INFO]: [QuickShop] Downloading version manifest...
[02:48:37] [Thread-20/INFO]: [QuickShop] Downloading version index...
[02:48:38] [Thread-20/WARN]: [QuickShop] Cannot get file hash for language en_, fallback to en_us...
[02:48:38] [Thread-20/WARN]: [QuickShop] Cannot download require files, some items/blocks/potions/enchs language will use default English name.
**[02:48:38] [Server thread/WARN]: [QuickShop] Loaded class net.minidev.json.parser.ParseException from Geyser-Spigot v1.2.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.**
[02:48:38] [Server thread/ERROR]: Cannot load plugins/QuickShop/messages.json
org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
at org.maxgamer.quickshop.fileportlek.newest.json.json.JsonConfiguration.loadFromString(JsonConfiguration.java:62) ~[?:?]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.maxgamer.quickshop.fileportlek.newest.json.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:110) ~[?:?]
at org.maxgamer.quickshop.fileportlek.newest.json.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:131) ~[?:?]
at org.maxgamer.quickshop.fileportlek.old.JSONFile.reload(JSONFile.java:54) ~[?:?]
at org.maxgamer.quickshop.fileportlek.old.FileEnvelope.create(FileEnvelope.java:76) ~[?:?]
at org.maxgamer.quickshop.util.MsgUtil.loadCfgMessages(MsgUtil.java:271) ~[?:?]
at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:677) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: net.minidev.json.parser.ParseException: Unexpected token
at position 9968.
at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:163) ~[?:?]
at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58) ~[?:?]
at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:39) ~[?:?]
at net.minidev.json.parser.JSONParser.parse(JSONParser.java:263) ~[?:?]
at org.maxgamer.quickshop.fileportlek.newest.json.json.JsonConfiguration.loadFromString(JsonConfiguration.java:60) ~[?:?]
... 18 more
[02:48:39] [Server thread/ERROR]: [QuickShop] Could not load json file lang/en-US/messages.json
org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
at org.maxgamer.quickshop.fileportlek.newest.json.json.JsonConfiguration.loadFromString(JsonConfiguration.java:62) ~[?:?]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.maxgamer.quickshop.fileportlek.old.JSONFile.reload(JSONFile.java:58) ~[?:?]
at org.maxgamer.quickshop.fileportlek.old.FileEnvelope.create(FileEnvelope.java:76) ~[?:?]
at org.maxgamer.quickshop.util.MsgUtil.loadCfgMessages(MsgUtil.java:271) ~[?:?]
at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:677) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: net.minidev.json.parser.ParseException: Unexpected token
at position 16581.
at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:163) ~[?:?]
at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58) ~[?:?]
at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:39) ~[?:?]
at net.minidev.json.parser.JSONParser.parse(JSONParser.java:263) ~[?:?]
at org.maxgamer.quickshop.fileportlek.newest.json.json.JsonConfiguration.loadFromString(JsonConfiguration.java:60) ~[?:?]
... 15 more
[02:48:40] [Server thread/INFO]: [QuickShop] Invaild message: translation-author
[02:48:40] [Server thread/INFO]: [QuickShop] Invaild message: translation-contributors
[02:48:40] [Server thread/INFO]: [QuickShop] Invaild message: translation-country
[02:48:40] [Server thread/INFO]: [QuickShop] Completed to load plugin translations files.
[02:48:40] [Server thread/INFO]: [QuickShop] Starting loading items translation...
[02:48:40] [Server thread/INFO]: [QuickShop] Complete to load items translation.
[02:48:40] [Server thread/INFO]: [QuickShop] Starting loading enchantments translation...
[02:48:40] [Server thread/INFO]: [QuickShop] Complete to load enchantments translation.
[02:48:40] [Server thread/INFO]: [QuickShop] Starting loading potions translation...
[02:48:40] [Server thread/INFO]: [QuickShop] Complete to load potions effect translation. 
```

After relocating, every work again, but relocating using the undocumented stuff form there: https://stackoverflow.com/questions/27535909/why-does-relocation-with-the-maven-shade-plugin-not-work
So after this, this commit fix it compeletly, including previous sentry loading error:  https://github.com/Ghost-chu/QuickShop-Reremake/commit/69ce80fe8fae9e44965e861a2f053079f6594d11
