### ISSUE TITLE
startup optimisation? 

### ISSUE THREAD

**Issue by jordanwilliams1** [Ghost-chu/QuickShop-Reremake#75]
Hello there, If your database has loads of shops it can cause the plugin a while to load. Do you think you could add some sort of option where the plugin will load up straight away and then start loading the shops in the background? 

`[08:02:00] [Server thread/INFO]: [QuickShop] Loading shops from database...`

`[08:02:26] [Server thread/INFO]: [QuickShop] Loaded 9221 shops.`

**Comment by Ghost-chu** [comment]
asynchronous is very danger, is will cause data losing, server crashing, and bukkit disallow use Bukkit API in asynchronous threads, so it maybe hard to do.

You should find out why it loads so slowly, maybe is database performance bad, disk I/O, or just processing readed data.

But anyway, this maybe cause have long load time, but it won't broken your server and data.

I will try improve the load speed, thanks for advice :)

**Comment by jordanwilliams1** [comment]
I'm pretty sure the jobs plugin use's some sort of method to loading everyone's jobs in the background. I Used to see it in my console a while back after the server loaded up. I Don't know if that would help you :P


"1000/6000 Jobs loadded"
"2000/6000 jobs loadded" etc, etc

**Comment by NieOGRL** [comment]
[20:11:01 ERROR]: Could not pass event InventoryDragEvent to QuickShop vReremake 1.4.3.5
java.lang.NullPointerException: null
        at org.maxgamer.quickshop.Shop.InventoryPreview.isPreviewItem(InventoryPreview.java:66) ~[?:?]
        at org.maxgamer.quickshop.Listeners.CustomInventoryListener.invEvent(CustomInventoryListener.java:48) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor263.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.1.jar:git-Paper-26]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.Container.a(Container.java:251) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2297) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:971) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.1.jar:git-Paper-26]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by Ghost-chu** [comment]
@NieOGRL redownload new jar

**Comment by Ghost-chu** [comment]
finished in latest build
