### ISSUE TITLE
报错了，最新版本1.2.2，我用的linux，backup文件也生成在了plugin目录下

### ISSUE THREAD

**Issue by mcpanglei** [Ghost-chu/QuickShop-Reremake#8]
[07:02:26 INFO]: [QuickShop] Enabling QuickShop vReremake 1.2.1
[07:02:26 INFO]: [QuickShop] Quickshop Reremake by Ghost_chu(Minecraft SunnySide Server Community)
[07:02:26 INFO]: [QuickShop] THIS VERSION ONLY SUPPORT BUKKIT API 1.13-1.13.x VERSION!
[07:02:26 INFO]: [QuickShop] Author:Ghost_chu
[07:02:26 INFO]: [QuickShop] Original author:Netherfoam, Timtower, KaiNoMood
[07:02:26 INFO]: [QuickShop] Let's us start load plugin
[07:02:26 INFO]: [QuickShop] Found permission provider.
[07:02:26 INFO]: [QuickShop] Metrics is disabled, Skipping...
[07:02:26 INFO]: [QuickShop] Starting item scheduler
[07:02:26 INFO]: [QuickShop] Limit cfg found...
[07:02:26 INFO]: [QuickShop] Limits.use: true
[07:02:26 INFO]: [QuickShop] {quickshop.vip2=30, quickshop.vip3=50, quickshop=0, quickshop.vip=20}
[07:02:26 INFO]: [QuickShop] Loading shops from database...
[07:02:26 INFO]: [QuickShop] Complete to load Itemname i18n.
[07:02:26 INFO]: [QuickShop] Starting loading Enchantment i18n...
[07:02:26 INFO]: [QuickShop] Complete to load enchname i18n.
[07:02:26 INFO]: [QuickShop] Starting loading Potion i18n...
[07:02:26 INFO]: [QuickShop] Complete to load potionname i18n.
[07:02:26 ERROR]: [QuickShop] Error loading a shop! Coords: Location[mydipi (-757, 65, -853)] Item: DIAMOND...
[07:02:26 ERROR]: [QuickShop] Are you running quickshop in 1.13 and use QuickShop before 1.13 Minecraft Version?
[07:02:26 ERROR]: [QuickShop] ===========Error Reporting Start===========
[07:02:26 ERROR]: [QuickShop] #Java throw >>
[07:02:26 ERROR]: [QuickShop] StackTrace:
[07:02:26 WARN]: java.lang.NullPointerException
[07:02:26 WARN]:        at org.bukkit.Location.getBlock(Location.java:100)
[07:02:26 WARN]:        at org.maxgamer.quickshop.Shop.ShopManager.addShop(ShopManager.java:172)
[07:02:26 WARN]:        at org.maxgamer.quickshop.Shop.ShopManager.loadShop(ShopManager.java:80)
[07:02:26 WARN]:        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:369)
[07:02:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:02:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[07:02:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[07:02:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:435)
[07:02:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:349)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:616)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:578)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:793)
[07:02:26 WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:02:26 ERROR]: [QuickShop] #Shop data >>
[07:02:26 ERROR]: [QuickShop] Location: mydipi;(X:-757, Y:65, Z:-853)
[07:02:26 ERROR]: [QuickShop] Item: DIAMONDMetaData: org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$1@33c046a
[07:02:26 ERROR]: [QuickShop] Owner: 7f48e47a-5ee5-3cdf-bcb6-1772e6ea6bb6(7f48e47a-5ee5-3cdf-bcb6-1772e6ea6bb6)
[07:02:26 ERROR]: [QuickShop] BukkitWorld: WARNING:World not exist! [mydipi]
[07:02:26 ERROR]: [QuickShop] Target Block: Can't get block!
[07:02:26 ERROR]: [QuickShop] #Database info >>
[07:02:26 ERROR]: [QuickShop] Connected:true
[07:02:26 ERROR]: [QuickShop] Read Only:true
[07:02:26 ERROR]: [QuickShop] Client Info:{}
[07:02:26 ERROR]: [QuickShop] Read Only:true
[07:02:26 ERROR]: [QuickShop] #Debuging >>
[07:02:26 ERROR]: [QuickShop] Runnnig on step: Loading shop to memory
[07:02:26 ERROR]: [QuickShop] #Tips >>
[07:02:26 ERROR]: [QuickShop] Please report this issues to author, And you database will auto backup!
[07:02:26 ERROR]: [QuickShop] Failed to backup! (File not found)
[07:02:26 WARN]: java.io.FileNotFoundException: /home/HAIYANG/DIPI/plugins/QuickShop\shop.db (没有那个文件或目录)
[07:02:26 WARN]:        at java.io.FileInputStream.open0(Native Method)
[07:02:26 WARN]:        at java.io.FileInputStream.open(FileInputStream.java:195)
[07:02:26 WARN]:        at java.io.FileInputStream.<init>(FileInputStream.java:138)
[07:02:26 WARN]:        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:440)
[07:02:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:02:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[07:02:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[07:02:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:435)
[07:02:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:349)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:616)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:578)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311)
[07:02:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:793)
[07:02:26 WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:02:26 ERROR]: [QuickShop] Failed to backup! (Copy)
[07:02:26 ERROR]: Error occurred while enabling QuickShop vReremake 1.2.1 (Is it up to date?)
java.lang.NullPointerException: null
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:448) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.1.jar:git-Paper-273]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.1.jar:git-Paper-273]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-273]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:435) ~[patched_1.13.1.jar:git-Paper-273]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:349) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:616) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:578) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:793) ~[patched_1.13.1.jar:git-Paper-273]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[07:02:26 INFO]: [QuickShop] Disabling QuickShop vReremake 1.2.1

**Comment by Ghost-chu** [comment]
你是否有世界名为mydipi?

**Comment by Ghost-chu** [comment]
qs无法取得这个商店(世界不存在) 所以商店加载失败了

**Comment by Ghost-chu** [comment]
建议使用Multiverse-Core插件加载世界，如果您已经使用了，请下载v1.2.3-beta2进行测试(**务必做好备份！**)

**Comment by mcpanglei** [comment]
好的，我晚上测一下，现在在线比较多，不能测

**Comment by Ghost-chu** [comment]
long time no reply and this issue may already fixed in lastet build,if still notworking,please create a new issue.
