### ISSUE TITLE
An error occurs when the price is NaN.

### ISSUE THREAD

**Issue by snake0053** [Ghost-chu/QuickShop-Reremake#82]
When creating a shop with QuickShop, entering NaN for the price results in an error.
However, shops are created and can not be purchased or sold.
```
[QuickShop] [DEBUG] [org.maxgamer.quickshop.Database.Database] [execute] INSERT INTO shops (owner, price, itemConfig, x, y, z, world, unlimited, type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
[QuickShop] [DEBUG] [org.maxgamer.quickshop.Database.BufferStatement] [init] INSERT INTO shops (owner, price, itemConfig, x, y, z, world, unlimited, type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
[Essentials] Failed to display NaN: null
java.lang.NumberFormatException: null
        at java.math.BigDecimal.<init>(BigDecimal.java:497) ~[?:1.8.0_212]
        at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[?:1.8.0_212]
        at java.math.BigDecimal.<init>(BigDecimal.java:809) ~[?:1.8.0_212]
        at java.math.BigDecimal.valueOf(BigDecimal.java:1277) ~[?:1.8.0_212]
        at com.earth2me.essentials.api.Economy.format(Economy.java:355) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.format(Economy_Essentials.java:215) ~[?:?]
        at org.maxgamer.quickshop.Economy.Economy_Vault.format(Economy_Vault.java:79) ~[?:?]
        at org.maxgamer.quickshop.Economy.Economy.format(Economy.java:32) ~[?:?]
        at org.maxgamer.quickshop.Util.Util.format(Util.java:512) ~[?:?]
        at org.maxgamer.quickshop.Shop.ContainerShop.setSignText(ContainerShop.java:528) ~[?:?]
        at org.maxgamer.quickshop.Shop.ShopManager.createShop(ShopManager.java:93) ~[?:?]
        at org.maxgamer.quickshop.Shop.ShopManager.actionCreate(ShopManager.java:692) ~[?:?]
        at org.maxgamer.quickshop.Shop.ShopManager.access$000(ShopManager.java:33) ~[?:?]
        at org.maxgamer.quickshop.Shop.ShopManager$1.run(ShopManager.java:367) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
```
[QuickShop] [DEBUG] [org.maxgamer.quickshop.Database.BufferStatement] [prepareStatement] INSERT INTO shops (owner, price, itemConfig, x, y, z, world, unlimited, type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: shops.price)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.execute(DB.java:854)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:56)
        at org.maxgamer.quickshop.Database.SQLiteCore.flush(SQLiteCore.java:83)
        at org.maxgamer.quickshop.Database.SQLiteCore$1.run(SQLiteCore.java:106)
```

**Comment by Ghost-chu** [comment]
NaN not a vaild price, you should fill the price with a vaild number, e.g 1.37, 136.93
