### ISSUE TITLE
[BUG] IllegalStateException: Recursive update

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#834]
QuickShop dev 683

Caused by a hopper on a shop container with Caffeine cache change? QuickShop was spamming this error non-stop until I forced a server restart. TPS was also taking a dive into the ground.

![link](https://i.imgur.com/V08nC9F.png)

https://paste.gg/p/anonymous/b136ecee19f6461b9d0836d0caf74995/files/d793a74913d441f8a494df000cd5cc4d/raw
```
[03:11:21] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to QuickShop v4.0.7.4
[03:11:21] [Server thread/ERROR]: Suspected Plugins: 
[03:11:21] [Server thread/ERROR]: 	QuickShop{enabled,ver=4.0.7.4,path=plugins/QuickShop-4.0.7.4.jar}
[03:11:21] [Server thread/ERROR]: Exception details below: 
java.lang.IllegalStateException: Recursive update
	at java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1863) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.remove(BoundedLocalCache.java:2102) ~[?:?]
	at com.github.benmanes.caffeine.cache.LocalManualCache.invalidate(LocalManualCache.java:140) ~[?:?]
	at org.maxgamer.quickshop.Cache.setCache(Cache.java:89) ~[?:?]
	at org.maxgamer.quickshop.shop.ShopManager.getShopIncludeAttached_Fast(ShopManager.java:1376) ~[?:?]
	at org.maxgamer.quickshop.shop.ShopManager.getShopIncludeAttached(ShopManager.java:362) ~[?:?]
	at org.maxgamer.quickshop.shop.ShopManager.getShopIncludeAttached(ShopManager.java:345) ~[?:?]
	at org.maxgamer.quickshop.Cache.lambda$getCaching$0(Cache.java:64) ~[?:?]
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325) ~[?:?]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[?:?]
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[?:?]
	at org.maxgamer.quickshop.Cache.getCaching(Cache.java:60) ~[?:?]
	at org.maxgamer.quickshop.listener.ProtectionListenerBase.getShopRedstone(ProtectionListenerBase.java:54) ~[?:?]
	at org.maxgamer.quickshop.listener.ShopProtectionListener.onInventoryMove(ShopProtectionListener.java:249) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1102.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.callPushMoveEvent(TileEntityHopper.java:296) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.hopperPush(TileEntityHopper.java:218) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.k(TileEntityHopper.java:367) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.a(TileEntityHopper.java:156) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.tick(TileEntityHopper.java:118) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.World.tickBlockEntities(World.java:980) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:962) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1450) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:398) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1295) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1016) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab9fdca"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

Downgrading to QuickShop dev 672 (before Caffeine was re-added), doesn't seem to cause the error spam.

**Comment by Ghost-chu** [comment]
Please try https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/685/

**Comment by Ghost-chu** [comment]
edited: use build 687

**Comment by mibby** [comment]
Seems to be fixed and fine now, but hard to know what originally caused it. I'll let you know if it occurs again.
