### ISSUE TITLE
[BUG] Not all shops are loading - NumberFormatException: For input string: "1.0"

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#837]
QuickShop-Remake-SNAPSHOT dev 699

```
[09:32:04] [Server thread/INFO]: [QuickShop] Translator: Ghost_chu, Andre_601
[09:32:04] [Server thread/INFO]: [QuickShop] Contributors: Timtower, Netherfoam, KaiNoMood, Mgazul, JackTheChicken and Andre_601
[09:32:04] [Server thread/INFO]: [QuickShop] Language Zone: English (en_US)
[09:32:04] [Server thread/INFO]: [QuickShop] Completed to load plugin translations files.
[09:32:04] [Server thread/INFO]: [QuickShop] Loading items translations...
[09:32:04] [Server thread/INFO]: [QuickShop] Complete to load items translation.
[09:32:04] [Server thread/INFO]: [QuickShop] Loading enchantments translations...
[09:32:04] [Server thread/INFO]: [QuickShop] Complete to load enchantments translation.
[09:32:04] [Server thread/INFO]: [QuickShop] Loading potions translations...
[09:32:04] [Server thread/INFO]: [QuickShop] Complete to load potions effect translation.
[09:32:04] [Server thread/INFO]: [QuickShop] Successfully loaded PlaceHolderAPI support!
[09:32:04] [Server thread/INFO]: [QuickShop] Successfully loaded LWC support!
[09:32:04] [Server thread/INFO]: [QuickShop] Using Virtual item Display, loading ProtocolLib support...
[09:32:04] [Server thread/INFO]: [QuickShop] Successfully loaded ProtocolLib support!
[09:32:04] [Server thread/INFO]: [QuickShop] Selected permission provider: Bukkit
[09:32:04] [Server thread/INFO]: [QuickShop] Manager now selected: BukkitEventManager
[09:32:04] [Server thread/INFO]: [QuickShop] Loading shops from the database...
[09:32:04] [Server thread/INFO]: [QuickShop] Used 1ms to fetch all shops from the database.
[09:32:04] [Server thread/WARN]: [QuickShop] ##########FAILED TO LOAD SHOP##########
[09:32:04] [Server thread/WARN]: [QuickShop]   >> Error Info:
[09:32:04] [Server thread/WARN]: [QuickShop] For input string: "1.0"
[09:32:04] [Server thread/WARN]: [QuickShop]   >> Error Trace
[09:32:04] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "1.0"
[09:32:04] [Server thread/WARN]: 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
[09:32:04] [Server thread/WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:652)
[09:32:04] [Server thread/WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
[09:32:04] [Server thread/WARN]: 	at org.maxgamer.quickshop.shop.ContainerShop.<init>(ContainerShop.java:154)
[09:32:04] [Server thread/WARN]: 	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:111)
[09:32:04] [Server thread/WARN]: 	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:76)
[09:32:04] [Server thread/WARN]: 	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:786)
[09:32:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:32:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[09:32:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[09:32:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500)
[09:32:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414)
[09:32:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:467)
[09:32:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:260)
[09:32:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:946)
[09:32:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176)
[09:32:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[09:32:04] [Server thread/WARN]: [QuickShop]   >> Target Location Info
[09:32:04] [Server thread/WARN]: [QuickShop] Location: NULL
[09:32:04] [Server thread/WARN]: [QuickShop] Block: NULL
[09:32:04] [Server thread/WARN]: [QuickShop] #######################################
[09:32:04] [Server thread/INFO]: [QuickShop] Registering Listeners...
[09:32:04] [Server thread/INFO]: [QuickShop] Cleaning MsgUtils...
[09:32:04] [Server thread/INFO]: [QuickShop] Cleaning purchase messages from the database that are over a week old...
[09:32:04] [Server thread/INFO]: [QuickShop] QuickShop Loaded! 290 ms.
[09:32:04] [Server thread/INFO]: [QuickShop] Log actions is enabled, actions will log in the qs.log file!
```

This causes many shops to not display their display item in-game or even function. As if it stops loading shops once it reaches the break.

Downgrading to dev 688 (version I used prior) outputs this error, also with shops not working.
```
[09:57:27] [Server thread/WARN]: [QuickShop] ##########FAILED TO LOAD SHOP##########
[09:57:27] [Server thread/WARN]: [QuickShop]   >> Error Info:
[09:57:27] [Server thread/WARN]: [QuickShop] class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap')
[09:57:27] [Server thread/WARN]: [QuickShop]   >> Error Trace
[09:57:27] [Server thread/WARN]: java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap')
[09:57:27] [Server thread/WARN]: 	at org.maxgamer.quickshop.shop.ContainerShop.<init>(ContainerShop.java:154)
[09:57:27] [Server thread/WARN]: 	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:112)
[09:57:27] [Server thread/WARN]: 	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:77)
[09:57:27] [Server thread/WARN]: 	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:795)
[09:57:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:57:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[09:57:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[09:57:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500)
[09:57:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414)
[09:57:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:467)
[09:57:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:260)
[09:57:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:946)
[09:57:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176)
[09:57:27] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[09:57:27] [Server thread/WARN]: [QuickShop]   >> Target Location Info
[09:57:27] [Server thread/WARN]: [QuickShop] Location: NULL
[09:57:27] [Server thread/WARN]: [QuickShop] Block: NULL
[09:57:27] [Server thread/WARN]: [QuickShop] #######################################
[09:57:27] [Server thread/INFO]: [QuickShop] Registering Listeners...
[09:57:27] [Server thread/INFO]: [QuickShop] Cleaning MsgUtils...
[09:57:27] [Server thread/INFO]: [QuickShop] Cleaning purchase messages from the database that are over a week old...
[09:57:27] [Server thread/INFO]: [QuickShop] QuickShop Loaded! 278 ms.
[09:57:27] [Server thread/INFO]: [QuickShop] Log actions is enabled, actions will log in the qs.log file!
```

**Comment by Ghost-chu** [comment]
This is a bug in dev builds that caused by our rewritting Extra Data API and we're know about that but we had no fix that yet.
In current state, the data saved as JSON and may cause some issues, we're planning migrate to YAML or TOML format and use base64 encoding it.
Unfortunately the shop data seems already damaged when use buggy snapshot.
You can edit database to purge all shops's extra field to fix shops.

**Comment by mibby** [comment]
Should the latest snapshot not be used for now then?

**Comment by Ghost-chu** [comment]
We never recommend user to use snapshot. The snapshot is automaticlly build when we push something to github. But in this case we may not test them at all, It may contains bugs or completely doesn't work or directly destory all data.
If you want test or try new feature, you can download it and install on test server.
But it shouldn't use in your online server. NEVER.





---Original---
