### ISSUE TITLE
用的数据库，加载出现下边报错，拿东西点箱子不会出现让你输入价格

### ISSUE THREAD

**Issue by mcpanglei** [Ghost-chu/QuickShop-Reremake#9]
[07:19:37 INFO]: [QuickShop] Enabling QuickShop vReremake 1.2.0
[07:19:37 INFO]: [QuickShop] Quickshop Reremake by Ghost_chu(Minecraft SunnySide Server Community)
[07:19:37 INFO]: [QuickShop] THIS VERSION ONLY SUPPORT BUKKIT API 1.13-1.13.x VERSION!
[07:19:37 INFO]: [QuickShop] Author:Ghost_chu
[07:19:37 INFO]: [QuickShop] Original author:Netherfoam, Timtower, KaiNoMood
[07:19:37 INFO]: [QuickShop] Let's us start load plugin
[07:19:37 INFO]: [QuickShop] Found permission provider.
[07:19:37 INFO]: [QuickShop] Metrics is disabled, Skipping...
[07:19:37 INFO]: [QuickShop] Starting item scheduler
[07:19:37 INFO]: [QuickShop] Limit cfg found...
[07:19:37 INFO]: [QuickShop] Limits.use: true
[07:19:37 INFO]: [QuickShop] {quickshop.vip2=30, quickshop.vip3=50, quickshop=0, quickshop.vip=20}
[07:19:37 INFO]: [QuickShop] Loading shops from database...
[07:19:37 INFO]: [QuickShop] Complete to load Itemname i18n.
[07:19:37 INFO]: [QuickShop] Starting loading Enchantment i18n...
[07:19:37 INFO]: [QuickShop] Complete to load enchname i18n.
[07:19:37 INFO]: [QuickShop] Starting loading Potion i18n...
[07:19:37 INFO]: [QuickShop] Complete to load potionname i18n.
[07:19:37 WARN]: java.lang.NullPointerException
[07:19:37 WARN]:        at org.bukkit.Location.getBlock(Location.java:100)
[07:19:37 WARN]:        at org.maxgamer.quickshop.Shop.ShopManager.addShop(ShopManager.java:172)
[07:19:37 WARN]:        at org.maxgamer.quickshop.Shop.ShopManager.loadShop(ShopManager.java:80)
[07:19:37 WARN]:        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:340)
[07:19:37 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:19:37 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[07:19:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[07:19:37 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:435)
[07:19:37 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:349)
[07:19:37 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:616)
[07:19:37 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:578)
[07:19:37 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[07:19:37 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311)
[07:19:37 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:793)
[07:19:37 WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:19:37 ERROR]: [QuickShop] Error loading a shop! Coords: mydipi (-757, 65, -853)...
[07:19:37 INFO]: [QuickShop] Skipping load this shop...

正常的话后边还有下班的日志，感觉就是报错后不再加载
[07:27:47 INFO]: [QuickShop] Loaded 0 shops.
[07:27:47 INFO]: [QuickShop] Registering Listeners
[07:27:47 WARN]: [QuickShop] Cleaning purchase messages from database that are over a week old...
[07:27:47 INFO]: [QuickShop] QuickShop loaded!

**Comment by Ghost-chu** [comment]
问题重复提交
