### ISSUE TITLE
[BUG]进入服务器极大几率会因数据包解析错误被踢出（Being kicked by packet decoding exception）

### ISSUE THREAD

**Issue by shuiqing2046** [Ghost-chu/QuickShop-Reremake#919]
### Describe the bug:
客户端几乎有百分百的可能性会在进服时退出

### To Reproduce:
版本从QuickShop-4.0.7.8到QuickShop-4.0.7.10三个版本都已测试出现这种情况(已经过反反复复的测试)，有时候可用正常进服,但在死亡自动重生或切换世界时触发该问题，客户端报错界面都一样，听别人对错误代码的解释是由于插件拦截登入数据包时候错误修改了数据包，导致客户端无法正常解析...

### Expected behavior:
服务器版本为 1.16.5 paper-629,最近本地测试更新了大量插件后才出现该问题，经过不断的排除确定是QuickShop的问题，目前正常可用版本为QuickShop-4.0.7.6.
服务端后台在客户端退出时并无任何报错信息.

### Screenshots:
![image](https://user-images.githubusercontent.com/28628358/116207614-a74ec600-a772-11eb-8f73-5b9f0a96459d.png)

**Comment by sandtechnology** [comment]
请给出客户端日志， 以及你paste的信息（/qs paste）和服务器环境（使用BC？单服务端？）

**Comment by shuiqing2046** [comment]
> 请给出客户端日志， 以及你paste的信息（/qs paste）和服务器环境（使用BC？单服务端？）

①.客户端日志: https://paste.ubuntu.com/p/6dYhh6ZxrH/
②.paste 信息: https://paste.ubuntu.com/p/fQ56Fhb2DS/
③.BC端及启动日志: https://paste.ubuntu.com/p/JHryD6YCWV/

**Comment by sandtechnology** [comment]
使用原版客户端是否还会如此？

**Comment by shuiqing2046** [comment]
> 使用原版客户端是否还会如此？

一样的问题
https://paste.ubuntu.com/p/GjrGnWcNcr/

**Comment by sandtechnology** [comment]
> 
> 
> > 使用原版客户端是否还会如此？
> 
> 一样的问题
> https://paste.ubuntu.com/p/GjrGnWcNcr/

>如果有，请给出forge客户端下的debug.log
将悬浮物设置（display-type）为1是否会解决？

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/937/
试试这个版本？下有版本号的就好

**Comment by sandtechnology** [comment]
如果还没试的话可以先试试这个版本：
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/938/

**Comment by shuiqing2046** [comment]
> 如果还没试的话可以先试试这个版本：
> https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/939/

该版本似乎并没有被正常加载，启动时候有一段报错内容

`[09:25:35 INFO]: [QuickShop] Enabling QuickShop v4.0.7.10
[09:25:35 INFO]: [QuickShop] QuickShop Reremake
[09:25:35 INFO]: [QuickShop] Starting plugin self-test, please wait...
[09:25:36 INFO]: [QuickShop] [OK] Signature Verify
[09:25:36 INFO]: [QuickShop] [OK] EnvChecker SelfTest
[09:25:36 INFO]: [QuickShop] [OK] Java Runtime Environment Version Test
[09:25:36 INFO]: [QuickShop] Running QuickShop-Reremake on NMS version v1_16_R3 For Minecraft version 1.16.5
[09:25:36 INFO]: [QuickShop] [OK] Spigot Based Server Test
[09:25:36 INFO]: [QuickShop] [OK] Old QuickShop Test
[09:25:36 INFO]: [QuickShop] [OK] ModdedServer Based Test
[09:25:36 INFO]: [QuickShop] [OK] JulySafe Test
[09:25:36 INFO]: [QuickShop] [OK] CoreSupport Test
[09:25:36 INFO]: [QuickShop] [OK] Virtual DisplayItem Support Test
[09:25:36 INFO]: [QuickShop] [OK] PersistentStorageApi Support Test
[09:25:36 INFO]: [QuickShop] [OK] PacketListenerAPI conflict Test
[09:25:36 INFO]: [QuickShop] Reading the configuration...
[09:25:36 INFO]: [QuickShop] Loading plugin translations files...
[09:25:36 INFO]: [QuickShop] No longer waiting file downloading because it now timed out, now downloading in background, please reset itemi18n.yml, potioni18n.yml and enchi18n.yml after download completed.
[09:25:36 INFO]: [QuickShop] Completed to load plugin translations files.
[09:25:36 INFO]: [QuickShop] Developers: PotatoCraft Studio, Netherfoam, Timtower, KaiNoMood, Ghost_chu, Mgazul, TiaraRinne, sandtechnology
[09:25:36 INFO]: [QuickShop] Original author: Netherfoam, Timtower, KaiNoMood
[09:25:36 INFO]: [QuickShop] Let's start loading the plugin
[09:25:36 INFO]: [QuickShop] Chat processor selected: BUNGEECHAT
[09:25:36 INFO]: [QuickShop] Loading plugin translations files...
[09:25:36 INFO]: [QuickShop] No longer waiting file downloading because it now timed out, now downloading in background, please reset itemi18n.yml, potioni18n.yml and enchi18n.yml after download completed.
[09:25:36 INFO]: [QuickShop] Completed to load plugin translations files.
[09:25:36 INFO]: [QuickShop] Loading items translations...
[09:25:36 INFO]: [QuickShop] Complete to load items translation.
[09:25:36 INFO]: [QuickShop] Loading enchantments translations...
[09:25:36 INFO]: [QuickShop] Complete to load enchantments translation.
[09:25:36 INFO]: [QuickShop] Loading potions translations...
[09:25:36 INFO]: [QuickShop] Complete to load potions effect translation.
[09:25:36 INFO]: [QuickShop] Successfully loaded OpenInv support!
[09:25:36 INFO]: [QuickShop] Successfully loaded PlaceHolderAPI support!
[09:25:36 INFO]: [QuickShop] Using Virtual item Display, loading ProtocolLib support...
[09:25:36 INFO]: [QuickShop] Successfully loaded ProtocolLib support!
[09:25:36 INFO]: [QuickShop] Selected permission provider: Bukkit
[09:25:36 ERROR]: Error occurred while enabling QuickShop v4.0.7.10 (Is it up to date?)
java.lang.NullPointerException: prefix is marked non-null but is null
        at org.maxgamer.quickshop.command.CommandContainer.<init>(CommandContainer.java:35) ~[?:?]
        at org.maxgamer.quickshop.command.CommandContainer$CommandContainerBuilder.build(CommandContainer.java:35) ~[?:?]
        at org.maxgamer.quickshop.command.CommandManager.<init>(CommandManager.java:54) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:724) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[09:25:36 INFO]: [QuickShop] Disabling QuickShop v4.0.7.10
[09:25:36 INFO]: [QuickShop] QuickShop is finishing remaining work, this may need a while...
[09:25:36 INFO]: [QuickShop] Please wait for the data to flush its data...`

`[09:35:57 INFO]: Azi issued server command: /qs
[09:35:57 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'qs' in plugin QuickShop v4.0.7.10 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2171) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1986) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1939) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/941/
这个版本应该好了

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/946/
如果还没测试的话可以试试这个版本 这个是会作为正式版发布的版本

**Comment by shuiqing2046** [comment]
> https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/946/
> 如果还没测试的话可以试试这个版本 这个是会作为正式版发布的版本

还是一样的情况哦
客户端日志: https://paste.ubuntu.com/p/zQPsfd4qPN/

**Comment by sandtechnology** [comment]
关闭 display-item-show-name 问题是否解决？

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by shuiqing2046** [comment]
关闭 display-item-show-name 问题依旧存在

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/948/
使用这个版本呢？

**Comment by shuiqing2046** [comment]
> https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/948/
> 使用这个版本呢？

QuickShop-4.0.7.11 #948

用了十几分钟测试,目前为止这个版本似乎已经正常,建议容我继续体验一阵子看看，晚些时候再反馈一下？

**Comment by sandtechnology** [comment]
> 
> 
> > https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/948/
> > 使用这个版本呢？
> 
> QuickShop-4.0.7.11 #948
> 
> 用了十几分钟测试,目前为止这个版本似乎已经正常,建议容我继续体验一阵子看看，晚些时候再反馈一下？

好的

**Comment by shuiqing2046** [comment]
非常感谢开发人员的热情和认真维护,经过小半天体验,问题应该已得到解决.3H+的时长体验未再出现数据包解析错误被踢出的状况.
