### ISSUE TITLE
PlayerInteractEvent error

### ISSUE THREAD

**Issue by Florianpal1** [Ghost-chu/QuickShop-Reremake#94]
``` [12:17:32 ERROR]: Could not pass event PlayerInteractEvent to QuickShop vReremake 1.4.4.4
java.lang.NullPointerException: null
at org.maxgamer.quickshop.Util.Util.canBeShop(Util.java:163) ~[?:?]
at org.maxgamer.quickshop.Listeners.LockListener.onClick(LockListener.java:28) ~[?:?] 
```

I use paper 1.14.2 version git-paper-59.
This error spams the console and arrives while not using the shops.

**Comment by Ghost-chu** [comment]
Update plugin version

**Comment by Ghost-chu** [comment]
Must given a /qs paste.
Make sure you already up-to-date.

**Comment by Florianpal1** [comment]
https://paste.ubuntu.com/p/jCzQpmwcpj/
