### ISSUE TITLE
[BUG] Server Can't Close when an exception was threw in stopping

### ISSUE THREAD

**Issue by Kovalski4** [Ghost-chu/QuickShop-Reremake#944]
### Describe the bug:
I get this warning when I shut down the server and the server won't shut down.

`org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:177) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:146) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter.sendError(RollbarErrorReporter.java:185) ~[?:?]
	at org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter$GlobalExceptionFilter.isLoggable(RollbarErrorReporter.java:332) ~[?:?]
	at java.util.logging.Logger.log(Logger.java:965) ~[?:?]
	at java.util.logging.Logger.doLog(Logger.java:1006) ~[?:?]
	at java.util.logging.Logger.log(Logger.java:1117) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.handlePluginException(SimplePluginManager.java:563) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:518) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:435) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:899) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:747) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1177) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

### To Reproduce:
1. Close server running with QuickShop Reremake - 1.16 Ready - Multi Currency 4.0.8.1 plugin

### Screenshots:
Leave this section body empty if no screenshots provided.

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- 【REPLACE ME TO PASTE LINK】

### Additional context:
Leave this section body empty if no additional context provided.

**Comment by sandtechnology** [comment]
Please provide the FULL log when stopping server

**Comment by Kovalski4** [comment]
This log is longer last part is looping and server can't close.
[2021-05-11-4.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/6458812/2021-05-11-4.log)

**Comment by sandtechnology** [comment]
This build should fix it: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/1027/

**Comment by Kovalski4** [comment]
Its fixed, I confirm
