### ISSUE TITLE
[BUG] I look the Problem

### ISSUE THREAD

**Issue by BackSam6348** [Ghost-chu/QuickShop-Reremake#963]
### To Reproduce:
1. Go to 'Just using /qs reload'
2. Click on 'none'
3. Scroll down to 'none'
> qs reload
[22:19:29 INFO]: 리로드 중...
[22:19:29 INFO]: [QuickShop] Disabling QuickShop v4.0.8.2
[22:19:29 INFO]: [QuickShop] QuickShop is finishing remaining work, this may need a while...
[22:19:29 INFO]: [QuickShop] Please wait for the data to flush its data...
[22:19:29 INFO]: [QuickShop] Enabling QuickShop v4.0.8.2
[22:19:29 WARN]: Enabled plugin with unregistered PluginClassLoader QuickShop v4.0.8.2
[22:19:29 INFO]: [QuickShop] QuickShop Reremake
[22:19:29 INFO]: [QuickShop] Starting plugin self-test, please wait...
[22:19:29 WARN]: [QuickShop] The signature not exists in QuickShop jar. The jar has been modified or you're running custom build.
[22:19:29 WARN]: [QuickShop] [STOP] Signature Verify: Security risk detected, QuickShop jar has been modified.
[22:19:29 INFO]: [QuickShop] [OK] Java Runtime Environment Version Test
[22:19:29 INFO]: [QuickShop] [OK] EnvChecker SelfTest
[22:19:29 INFO]: [QuickShop] Running QuickShop-Reremake on NMS version v1_16_R3 For Minecraft version 1.16.5
[22:19:29 INFO]: [QuickShop] [OK] Spigot Based Server Test
[22:19:29 WARN]: [QuickShop] Failed executing EnvCheckEntry [oldQuickShopTest]: Exception thrown out without caught. Something going wrong!
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:110) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:644) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:674) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.maxgamer.quickshop.command.subcommand.SubCommand_Reload.onCommand(SubCommand_Reload.java:39) ~[?:?]
        at org.maxgamer.quickshop.command.CommandManager.onCommand(CommandManager.java:406) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:454) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:421) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1401) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at org.maxgamer.quickshop.util.Util.isClassAvailable(Util.java:814) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.oldQuickShopTest(EnvironmentChecker.java:287) ~[?:?]
        ... 22 more
[22:19:29 WARN]: [QuickShop] [FAIL] oldQuickShopTest
[22:19:29 WARN]: [QuickShop] Failed executing EnvCheckEntry [moddedBasedTest]: Exception thrown out without caught. Something going wrong!
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:110) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:644) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:674) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.maxgamer.quickshop.command.subcommand.SubCommand_Reload.onCommand(SubCommand_Reload.java:39) ~[?:?]
        at org.maxgamer.quickshop.command.CommandManager.onCommand(CommandManager.java:406) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:454) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:421) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1401) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at org.maxgamer.quickshop.util.Util.isClassAvailable(Util.java:814) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.isForgeBasedServer(EnvironmentChecker.java:295) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.moddedBasedTest(EnvironmentChecker.java:309) ~[?:?]
        ... 22 more
[22:19:29 WARN]: [QuickShop] [FAIL] moddedBasedTest
[22:19:29 INFO]: [QuickShop] [OK] JulySafe Test
[22:19:29 INFO]: [QuickShop] [OK] CoreSupport Test
[22:19:29 INFO]: [QuickShop] [OK] Virtual DisplayItem Support Test
[22:19:29 INFO]: [QuickShop] [OK] PersistentStorageApi Support Test
[22:19:29 INFO]: [QuickShop] [OK] PacketListenerAPI conflict Test
[22:19:29 ERROR]: Error occurred while enabling QuickShop v4.0.8.2 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:652) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:674) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.maxgamer.quickshop.command.subcommand.SubCommand_Reload.onCommand(SubCommand_Reload.java:39) ~[?:?]
        at org.maxgamer.quickshop.command.CommandManager.onCommand(CommandManager.java:406) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:454) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:421) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1401) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[22:19:29 INFO]: [QuickShop] Disabling QuickShop v4.0.8.2
[22:19:29 INFO]: [QuickShop] QuickShop is finishing remaining work, this may need a while...
[22:19:29 INFO]: [QuickShop] Please wait for the data to flush its data...
[22:19:29 ERROR]: Error occurred while disabling QuickShop v4.0.8.2 (Is it up to date?)
java.io.IOException: Stream closed
        at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:51) ~[?:?]
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:158) ~[?:?]
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248) ~[?:?]
        at org.maxgamer.quickshop.watcher.LogWatcher.close(LogWatcher.java:91) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.onDisable(QuickShop.java:579) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:528) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.maxgamer.quickshop.command.subcommand.SubCommand_Reload.onCommand(SubCommand_Reload.java:39) ~[?:?]
        at org.maxgamer.quickshop.command.CommandManager.onCommand(CommandManager.java:406) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:454) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:421) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1401) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
        
### Expected behavior:
I just using /qs reload
and I using the Java 16 with Tuinity

### Screenshots:
Leave this section body empty if no screenshots provided.

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- https://cdn.discordapp.com/attachments/738308901937872918/847102446618411048/QuickShop.zip

### Additional context:
I using plugins list

[22:23:49 INFO]: Plugins (41): AAC5, AACAdditionPro, ClearLag, CoreProtect, CrackShot, DisableMe*, Essentials, Essentials_WarpGUI, EssentialsChat, EssentialsGeoIP, EssentialsProtect, GSit, HolographicDisplays, LockettePro, LuckPerms, Multiverse-Core, Multiverse-Inventories, MysqlEconomyBank, Orebfuscator, PingVersion*, PlayMoreSounds*, Playtimes*, ProtocolLib, QuickShop, RandomTeleport, Residence, Server_UUID_Ban, SkJade, SkQuery, skRayFall, Skript, Taxes, TheNewEconomy, UberEnchant, Vault, Votifier, VotingPlugin, VTV1*, WorldBorder, WorldEdit, WorldGuard

**Comment by sandtechnology** [comment]
It's because you have replace the plugin jar or server jar, not our issue.

**Comment by Ghost-chu** [comment]
Replace jar or reload whole server while server running is unsupported.
